apiVersion: apps/v1
kind: Deployment
metadata: 
  name: my-api-deployment
  labels:
    app: api
spec: 
  replicas: 2
  selector: 
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec: 
      containers:
      - name: api
        image: lisarebecca/sample-api:1.1
        ports:
        - containerPort: 6000