version: "3.7"

services:
  app:
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
    links:
      - db
    restart: always
    environment: 
      - VERSION=1
  db:
    image: mongo:latest
    hostname: test_mongodb
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=animal_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
      #- mongo-data:/data/db 
    ports:
      - 27017:27017
# volumes:
#   mongo-data:
#     driver: local